"""SQL generation for VecAdvisor++ recommendations.

Produces concrete, executable SQL statements for index creation,
session settings, auxiliary indexes, and vector queries.
"""

from src.advisor.rules import Recommendation


def generate_create_index_sql(
    recommendation: Recommendation,
    table_name: str,
    column: str = "embedding",
) -> str | None:
    """Generate CREATE INDEX SQL for the recommended vector index.

    Args:
        recommendation: Advisor recommendation.
        table_name: Target table.
        column: Vector column name.

    Returns:
        SQL string or None if no index recommended.
    """
    if recommendation.index_type == "none":
        return None

    index_name = f"idx_{table_name}_{recommendation.index_type}"

    if recommendation.index_type == "hnsw":
        m = recommendation.build_params.get("m", 16)
        ef_construction = recommendation.build_params.get("ef_construction", 128)
        return (
            f"CREATE INDEX {index_name} ON {table_name} "
            f"USING hnsw ({column} vector_l2_ops) "
            f"WITH (m = {m}, ef_construction = {ef_construction});"
        )
    elif recommendation.index_type == "ivfflat":
        lists = recommendation.build_params.get("lists", 1000)
        return (
            f"CREATE INDEX {index_name} ON {table_name} "
            f"USING ivfflat ({column} vector_l2_ops) "
            f"WITH (lists = {lists});"
        )
    return None


def generate_session_settings_sql(recommendation: Recommendation) -> list[str]:
    """Generate SET statements for session-level parameters.

    Args:
        recommendation: Advisor recommendation.

    Returns:
        List of SET SQL statements.
    """
    statements = []

    # Index-specific query params
    if recommendation.index_type == "hnsw":
        ef_search = recommendation.query_params.get("ef_search", 40)
        statements.append(f"SET hnsw.ef_search = {ef_search};")
    elif recommendation.index_type == "ivfflat":
        probes = recommendation.query_params.get("probes", 10)
        statements.append(f"SET ivfflat.probes = {probes};")

    # General session settings
    for param, value in recommendation.session_settings.items():
        statements.append(f"SET {param} = '{value}';")

    return statements


def generate_auxiliary_index_sql(
    recommendation: Recommendation, table_name: str
) -> list[str]:
    """Generate CREATE INDEX SQL for auxiliary B-tree indexes.

    Args:
        recommendation: Advisor recommendation.
        table_name: Target table.

    Returns:
        List of CREATE INDEX SQL statements.
    """
    statements = []
    for aux in recommendation.auxiliary_indexes:
        col = aux["column"]
        idx_name = f"idx_{table_name}_{col}_btree"
        statements.append(
            f"CREATE INDEX IF NOT EXISTS {idx_name} ON {table_name} ({col});"
        )
    return statements


def generate_query_sql(
    table_name: str,
    query_vector_placeholder: str = "%s",
    filter_clause: str | None = None,
    k: int = 10,
    column: str = "embedding",
) -> str:
    """Generate a vector similarity query SQL template.

    Args:
        table_name: Table to query.
        query_vector_placeholder: Placeholder for the query vector.
        filter_clause: Optional WHERE clause (without 'WHERE').
        k: Number of results.
        column: Vector column name.

    Returns:
        SQL query string.
    """
    where = f"WHERE {filter_clause}\n    " if filter_clause else ""
    return (
        f"SELECT id, {column} <-> {query_vector_placeholder}::vector AS distance\n"
        f"FROM {table_name}\n"
        f"    {where}"
        f"ORDER BY {column} <-> {query_vector_placeholder}::vector\n"
        f"LIMIT {k};"
    )


def generate_partition_ddl_sql(
    recommendation: Recommendation,
    table_name: str,
    dim: int,
    column: str = "embedding",
) -> str:
    """Generate DDL for a LIST-partitioned table with per-partition vector indexes.

    Outputs:
      1. CREATE TABLE … PARTITION BY LIST (col)  — parent table
      2. CREATE TABLE child PARTITION OF parent FOR VALUES IN (v)  — one per partition
      3. CREATE INDEX … USING hnsw … ON child  — per-partition vector index

    The partition values are assumed to be 0-based consecutive integers
    (0, 1, …, n_partitions-1), which matches the synthetic ``category_N``
    columns generated by ``generate_synthetic_attributes()``.

    Args:
        recommendation: Advisor recommendation with ``use_partitioning=True``.
        table_name: Target table name.
        dim: Vector dimensionality (needed for the CREATE TABLE statement).
        column: Vector column name.

    Returns:
        Complete DDL SQL string, or empty string when partitioning is disabled.
    """
    if not recommendation.use_partitioning:
        return ""

    part_col = recommendation.partition_column
    n_parts = recommendation.n_partitions
    idx_type = recommendation.index_type  # usually "hnsw"

    lines = [
        f"-- ── Partitioned Table DDL ─────────────────────────────────────",
        f"-- LIST partition by '{part_col}' ({n_parts} partitions)",
        "",
        f"-- Step 1: Create parent table (no SERIAL primary key on partitioned tables)",
        f"DROP TABLE IF EXISTS {table_name} CASCADE;",
        f"CREATE TABLE {table_name} (",
        f"    id            INT,",
        f"    {column}      vector({dim}),",
        f"    {part_col}    INT",
        f") PARTITION BY LIST ({part_col});",
        "",
        f"-- Step 2: Create child partitions (values 0 .. {n_parts - 1})",
    ]
    for v in range(n_parts):
        child = f"{table_name}_p{v}"
        lines.append(
            f"CREATE TABLE {child} PARTITION OF {table_name} FOR VALUES IN ({v});"
        )

    lines.append("")
    lines.append(f"-- Step 3: Create {idx_type.upper()} index on each partition")

    if idx_type == "hnsw":
        m = recommendation.build_params.get("m", 16)
        ef = recommendation.build_params.get("ef_construction", 128)
        for v in range(n_parts):
            child = f"{table_name}_p{v}"
            idx_name = f"idx_{child}_{idx_type}"
            lines.append(
                f"CREATE INDEX {idx_name} ON {child} "
                f"USING hnsw ({column} vector_l2_ops) "
                f"WITH (m = {m}, ef_construction = {ef});"
            )
    elif idx_type == "ivfflat":
        lists = recommendation.build_params.get("lists", 100)
        for v in range(n_parts):
            child = f"{table_name}_p{v}"
            idx_name = f"idx_{child}_{idx_type}"
            lines.append(
                f"CREATE INDEX {idx_name} ON {child} "
                f"USING ivfflat ({column} vector_l2_ops) "
                f"WITH (lists = {lists});"
            )

    lines.append("")
    lines.append("-- Example query (partition pruning kicks in automatically)")
    lines.append(
        f"SELECT id, {column} <-> '[...]'::vector AS distance"
    )
    lines.append(f"FROM {table_name}")
    lines.append(f"WHERE {part_col} = <value>")
    lines.append(f"ORDER BY {column} <-> '[...]'::vector")
    lines.append("LIMIT 10;")

    return "\n".join(lines)


def generate_full_recommendation_sql(
    recommendation: Recommendation,
    table_name: str,
    column: str = "embedding",
) -> str:
    """Generate the complete set of SQL statements for a recommendation.

    Args:
        recommendation: Advisor recommendation.
        table_name: Target table.
        column: Vector column name.

    Returns:
        Complete SQL string with all statements.
    """
    lines = ["-- VecAdvisor++ Recommended Configuration", ""]

    # Partitioned table DDL (emitted before session settings when applicable)
    if recommendation.use_partitioning:
        # Use a placeholder dim=128; callers that know the real dim can call
        # generate_partition_ddl_sql() directly with the correct value.
        part_ddl = generate_partition_ddl_sql(recommendation, table_name, 128, column)
        if part_ddl:
            lines.append(part_ddl)
            lines.append("")

    # Session settings
    session_stmts = generate_session_settings_sql(recommendation)
    if session_stmts:
        lines.append("-- Session Settings")
        lines.extend(session_stmts)
        lines.append("")

    # Main vector index (only for non-partitioned tables; partitioned DDL
    # already includes the per-partition index statements above)
    index_sql = generate_create_index_sql(recommendation, table_name, column)
    if recommendation.use_partitioning:
        # Partition DDL (including per-partition indexes) already written above.
        pass
    elif index_sql:
        lines.append("-- Vector Index")
        lines.append(index_sql)
        lines.append("")
    else:
        # Distinguish pre-filter strategy (has filter B-tree indexes) from a
        # plain small-dataset sequential scan (no auxiliary indexes needed).
        if recommendation.auxiliary_indexes:
            lines.append(
                "-- Pre-filter strategy: no vector index created."
            )
            lines.append(
                "-- PostgreSQL will use the B-tree index(es) below to materialise"
            )
            lines.append(
                "-- the filtered subset, then compute exact distances on that subset."
            )
        else:
            lines.append(
                "-- No vector index recommended (dataset small enough for sequential scan)."
            )
        lines.append("")

    # Auxiliary indexes
    aux_stmts = generate_auxiliary_index_sql(recommendation, table_name)
    if aux_stmts:
        lines.append("-- Auxiliary Indexes (for filter columns)")
        lines.extend(aux_stmts)
        lines.append("")

    # Example query
    lines.append("-- Example Query")
    lines.append(generate_query_sql(table_name, "'[...]'", None, 10, column))

    return "\n".join(lines)
